### PR TITLE
Update 1.00.00-intro.adoc

### PR DESCRIPTION
**Pull request by RogerKWilliams**
Minor grammatical updates.

### CODE REVIEW

**Comment by CharlesTBetz** [comment]
I think I want to stay book-centric. People might use this book in courses of various types.

**Comment by CharlesTBetz** [comment]
i'll leave this open whilst we discuss :-) - thanks for all your great work!

**Comment by RogerKWilliams** [comment]
I agree with your point. Any way to just accept the other edit, or are updates "all or nothing"?

**Comment by CharlesTBetz** [comment]
Fixed it manually.

**Pull request closed without merging**
